project: https://github.com/qualcomm/resource-tuner

branches:
  main:
    modes:
      non-blocking:
        headers:
          - core/Client/APIs/Include/UrmAPIs.h
          - modula/Common/Include/Common.h
          - resource-tuner/extensions/Include/Extensions.h
      blocking:
          - modula/Common/Include/ErrCodes.h
          - modula/Common/Include/Utils.h
