project: https://github.com/qualcomm/resource-tuner

branches:
  main:
    modes:
      non-blocking:
        headers:
          - resource-tuner/Core/Modula/Common/Include/Common.h
          - resource-tuner/extensions/Include/Extensions.h
      blocking:
        headers:
          - resource-tuner/Core/Client/APIs/Include/UrmAPIs.h 
          - modula/Common/Include/*.h
